### ISSUE TITLE
"Path is too long" error when searching recursively

### ISSUE THREAD

**Issue by mattstermiller** [mattstermiller/koffee#140]
**Describe the bug**
Searching a directory tree that contains items that exceed the legacy windows path length limit throws an unhandled exception:

> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
>    at System.IO.PathHelper.GetFullPathName()
>    at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
>    at System.IO.Path.GetFullPathInternal(String path)
>    at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
>    at Koffee.FileSystem.GetItems(Boolean foldersOnly, Path path)
>    at Utility.runAsync@26-1.Invoke(Unit _arg1)
>    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
>    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

This also happens when trying to open a folder with a path that exceeds the limit.

**To Reproduce**
1. See description

**Expected behavior**
Long paths should be supported.

**Workaround**
None

**Desktop (please complete the following information):**
 - Koffee Version: 0.7.0 WIP
 - OS: Windows 11

**Comment by mattstermiller** [comment]
- Windows apparently doesn't even allow long paths by default. Before _anything_ will allow you to work with long paths like Explorer, cmd, etc. you must set the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` to 1.
- .NET 4.6.2 allows long paths in the IO APIs if the registry allows it.

**Comment by mattstermiller** [comment]
I tested and confirmed that long paths > 260 chars can now be opened and show up in search results. Trying to _open_ things in such a folder, though, is another story. ProcessStartInfo does not support long paths in WorkingDirectory and there's a good chance other apps don't support long paths anyway. I will consider resolving that out-of-scope for this issue. If needed later, a new issue can be opened.
